version: '3.8'

services:
  repl:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: jugaadlang_repl
    stdin_open: true
    tty: true

  web:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: jugaadlang_web
    ports:
      - "5000:5000"
    entrypoint: ["jug", "run", "examples/10_web.jug"]
    volumes:
      - ../examples:/app/examples
