name: Issue Create Automate Message

on:
  issues:
    types: [opened]

jobs:
  auto-comment:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Comment on new issue
        uses: actions/github-script@v9
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: "Namaste! 🙏 Thanks for opening this issue! We're always looking for new ways to improve our *jugaad*. We'll review it shortly. In the meantime, please make sure you've provided enough context and steps to reproduce the issue if it's a bug. 🛠️"
            })
